default: &default
  adapter: redis
  url: redis://redis:6379/1

development:
  <<: *default
  channel_prefix: rate_limiter_development

test:
  <<: *default
  channel_prefix: rate_limiter_test

production:
  <<: *default
  channel_prefix: rate_limiter_production
